<a href="https://colab.research.google.com/github/JhericoBunao/Linear-Algebra-58020/blob/main/Applications_of_linear_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##System Of Linear Equeations##

##Systems of Linear Equation can be solved with and NumPy.

In [3]:
from scipy.linalg import solve
A=np.array([[4,5],[3,-2]])
print(A)
B=np.array([[7],[11]])
print(B)

X = np.linalg.inv(A).dot(B)
print(X)

[[ 4  5]
 [ 3 -2]]
[[ 7]
 [11]]
[[ 3.]
 [-1.]]


In [4]:
X = np.dot(inv_A,B)
print(X)

[[ 3.]
 [-1.]]


In [5]:
X= np.linalg.solve(A,B)
print(X)

[[ 3.]
 [-1.]]


In [8]:
from scipy.linalg import solve
X = solve(A,B)
print(X)

[[ 3.]
 [-1.]]
