<a href="https://colab.research.google.com/github/JhericoBunao/jhericobunao/blob/main/Array%2CVector%2Cmatrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
#create a 1x3 array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
#create a 2x3 matrix
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
#create a 3x3 matrix
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
#create a constant array with all values = 6 
d =np.full((4,4),6)
print(d)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [9]:
#create a diagonal matrix
e = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(e)
e = np.diagonal([[1,2,3],[4,5,6],[7,8,9]])
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [10]:
#addition of matrix
#create a 3x3 matrix
f = np.array([[1,2,3],[4,5,6]])
g = np.array([[1,2,3],[4,5,6]])
print(f+g)

[[ 2  4  6]
 [ 8 10 12]]


In [11]:
#addition of matrix
#create a 3x3 matrix
f = np.array([[1,2,3],[4,5,6]])
g = np.array([[1,2,3],[4,5,6]])
print(f-g)

[[0 0 0]
 [0 0 0]]
