<a href="https://colab.research.google.com/github/JhericoBunao/Linear-Algebra-58020/blob/main/Assessment_Determinant_of_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Week 9 Assessment (Determinant_of_Matrix)** 

In [6]:
import numpy as np
A = np.array([[1,2,-1],[4,6,-2],[-1,3,3]])
print("This is the given Matrix")
print(A)
print("The Determinant of Matrix A is")
print(np.linalg.det(A)) 
print("This is the Rounded answer of Matrix")
print(round(np.linalg.det(A)))

This is the given Matrix
[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]
The Determinant of Matrix A is
-13.999999999999996
This is the Rounded answer of Matrix
-14
