<a href="https://colab.research.google.com/github/JhericoBunao/Linear-Algebra-58020/blob/main/Final_Exam_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Problem 2. Solve each system##

In [7]:
#Problem 2. Solve each system
#error program

import numpy as np
A = np.array([3,-1,1], [9,-3,3], [-12,4,-4]]) #This is the given values for matrix 
B = np.array([8, 30, 108])
C = np.linalg.solve(A,B)
print (C) #This will print out the overall output of the program

#ANSWER: Based on my opinion and experience, this code doesn't work well because of the given values or elements inside the matrix. 
#if I'm not mistaken with the similar experience from what we have encountered during our discussion we have replaced value -1 instead of +1. 
#This wrong input of value leads to an error or not working program. maybe changes of the values or elements inside may change and make the program work.



SyntaxError: ignored

##PROBLEM 3.Eigenvalue & Eigenvector##


In [ ]:
##PROBLEM 3. 
##1.) Find the eigenvalue/s
##2.) Find the eigenvectors
import numpy as np

print("This is the sample matrix given") #This will show the given matrix
A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print(A)

J,M = np.linalg.eig(A)
print("The eignvalue for the given matrix is/are..\n",J) #This will give the value for eigenvalue
print("The eignvectors for the given matrix is/are..\n",M) #This will give the value for eigenvectors

This is the sample matrix given
[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]
The eignvalue for the given matrix is/are..
 [-1.  3.  2.]
The eignvectors for the given matrix is/are..
 [[ 3.01511345e-01 -7.07106781e-01  7.07106781e-01]
 [-9.04534034e-01  7.07106781e-01  1.53837015e-15]
 [-3.01511345e-01 -2.26120075e-15  7.07106781e-01]]
