<a href="https://colab.research.google.com/github/JhericoBunao/Linear-Algebra-58020/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Python program to inverse**

In [10]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
#Inverse
A = np.array([[1,2],[4,7]])
B=(np.linalg.inv(A))
print(B)

[[-7.  2.]
 [ 4. -1.]]


In [13]:
C=np.dot(A,B)
print(C)

[[1. 0.]
 [0. 1.]]


In [15]:
##python program to inverse a 3x3 matrix
## A = ([6,1,1],[4,-2,5],[2,8,7])

A= np.array([[6,1,1],[4,-2,5],[2,8,7]])
print(A)

B= np.transpose(A)
print(B)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]
