<a href="https://colab.research.google.com/github/JhericoBunao/Linear-Algebra-58020/blob/main/MIDTERM_EXAM_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Question 1.** **square matrix whose length is 5**

In [19]:
import numpy as np
A = np.array([[1,2,3,6,5],[4,5,6,1,3],[7,8,9,4,5],[2,4,7,8,9],[4,5,6,9,2]])

print(A)
lengthofmatrix = len(A) #This will measure the length of matrix
message = (f'\n The length of matrix is : {lengthofmatrix}') #This will indicate the length of matrix
print(message) #This will print out the overall output of matrix 


[[1 2 3 6 5]
 [4 5 6 1 3]
 [7 8 9 4 5]
 [2 4 7 8 9]
 [4 5 6 9 2]]

 The length of matrix is : 5


**Question 2. Elements below the principal diagonal are zero**

In [25]:
A = np.array([[0,2,3,6,5],[4,0,6,1,3],[7,8,0,4,5],[2,4,7,0,9],[4,5,6,9,0]])
print(A) #This will print out all the elements inside the array

print("This is the 0\'s values included in diagonal")
A = np.diagonal([[0,2,3,6,5],[4,0,6,1,3],[7,8,0,4,5],[2,4,7,0,9],[4,5,6,9,0]])
print(A) #This will print out the final ouput of 0 in Diagonal

[[0 2 3 6 5]
 [4 0 6 1 3]
 [7 8 0 4 5]
 [2 4 7 0 9]
 [4 5 6 9 0]]
This is the 0's values included in diagonal
[0 0 0 0 0]


**Question 3. square matrix which is symmetrical**

In [42]:
import numpy as np
matrix = np.array ([[1,2,3,6,5],[4,5,6,1,3],[7,8,9,4,5],[2,4,7,8,9],[4,5,6,9,2]]) #this code will provide symmetrical square matrix

print('The symmetrical square matrix')
print(matrix)

The symmetrical square matrix
[[1 2 3 6 5]
 [4 5 6 1 3]
 [7 8 9 4 5]
 [2 4 7 8 9]
 [4 5 6 9 2]]


**Question 4. What is the inverse of matrix C**


In [27]:
#inverse
C= np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(C) # This will print out the Original given element from matrix

D =(np.linalg.inv(C)) #This will print out the Inverse of matrix
print(D)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


**Question 5. determinant of the given matrix in Question 4?**

In [29]:
#determinant
C = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print("Here is the original given Matrix")
print(C) #This will display the original Matrix
print("The Determinant of Matrix C is")
print(np.linalg.det(C)) #This will print out the determinant of matrix from Q4
print("This is the Rounded answer of Matrix C")
print(round(np.linalg.det(C))) #This will print out the Rounded of determinant of matrix from Q4

Here is the original given Matrix
[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
The Determinant of Matrix C is
5.000000000000001
This is the Rounded answer of Matrix
5


**Question 6. roots of the linear equations**

In [40]:
#Roots
Equations = np.array([[5,4,1],
                      [10,9,4],
                      [10,13,15]])
print("This is the given problem in array.")
print(Equations) #This will print out the array

Constants = np.array([[[3.4],
                       [8.8],
                       [19.2]]])
print("This is the Roots of given problem")

roots = np.linalg.inv(Equations) @ Constants

print(roots) #This will print out the roots


This is the given problem in array.
[[ 5  4  1]
 [10  9  4]
 [10 13 15]]
This is the Roots of given problem
[[[0.2]
  [0.4]
  [0.8]]]
