<a href="https://colab.research.google.com/github/JhericoBunao/Linear-Algebra-58020/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Practical Lab Exam 1**

In [ ]:
import numpy as np
# a.)WY =  W * Y
W = np.array([[1,-3,],[2,-2],[3,1]])
Y = np.array([[1,2,0],[0,-1,2]])
print(np.dot(W,Y))

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


In [ ]:
# b.) Z+Z
Z = np.array([[0,1],[2,3]])
print(Z+Z)

[[0 2]
 [4 6]]


In [ ]:
# C.) 3X = 3 multiply to "X"
X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
print(3*X)

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


**Problem 2.Which of the following statements is true?** **THE ANSWER IS LETTER B**

---



In [62]:
# a. The product (YW)2 is not defined.
W = np.array([[1,-3,],[2,-2,],[3,1]])
Y = np.array([[1,2,0],[0,-1,2]])

YW = np.dot(Y,W)
print(YW*YW)

#Since it gave an output Letter "a" is FALSE

[[25 49]
 [16 16]]


In [59]:
# b. WY – X =
W = np.array([[1,-3,],[2,-2,],[3,1]])
Y = np.array([[1,2,0],[0,-1,2]])
X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
Final = np.dot(W,Y)
print(np.subtract(Final,X))

# Option Letter 'b' is TRUE Because it has the same output as the given choices.

[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]


In [60]:
# c. YW – Z^2 =
W = np.array([[1,-3,],[2,-2,],[3,1]])
Y = np.array([[1,2,0],[0,-1,2]])
Z = np.array([[0,1],[2,3]])
YW = np.dot(Y,W)
FZ = Z**2
print(np.subtract(YW,FZ))

#Different from the given choices Letter C is FALSE

[[ 5 -8]
 [ 0 -5]]


***THE FINAL ANSWER FOR NO.2 IS LETTER "b" b Is TRUE***