<a href="https://colab.research.google.com/github/JhericoBunao/Linear-Algebra-58020/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**BUNAO JHERICO MARVIN J. / 201912702 / LINEAR ALGEBRA FOR COMPUTER ENGINEERING LAB 0700-1000**

**Question 1: matrix "C"**

In [33]:
#Create a 4x4 Matrix...
import numpy as np
C = np.array([[1,2,3,5],[4,1,6,1],[7,8,1,2],[1,8,4,1]])
print(C)

print("This is the 1\'s values included in diagonal")
C = np.diagonal([[1,2,3,5],[4,1,6,1],[7,8,1,2],[1,8,4,1]])
print(C)

[[1 2 3 5]
 [4 1 6 1]
 [7 8 1 2]
 [1 8 4 1]]
This is the 1's values included in diagonal
[1 1 1 1]


**Question 2. doubles all the values of each element**

In [32]:
#Doubles all values of eax element
C = np.array([[1,2,3,5],[4,1,6,1],[7,8,1,2],[1,8,4,1]])
print("This is the Original Copy of Elemets from Q1.")
print(C)

print("here's The x2 value of the Elements from Q1.")
letsdoubleit = C*2
print(letsdoubleit)

This is the Original Copy of Elemets from Q1.
[[1 2 3 5]
 [4 1 6 1]
 [7 8 1 2]
 [1 8 4 1]]
here's The x2 value of the Elements from Q1.
[[ 2  4  6 10]
 [ 8  2 12  2]
 [14 16  2  4]
 [ 2 16  8  2]]


**Question 3, Find the cross Prdouct.**

In [31]:
#Question 3, Find the cross Prdouct.
import numpy as np
A = np.array([2,7,4])
B = np.array([3,9,8])
print("Here's the original value of given matrices")
print(A,B)

print("Here's the Cross Product of matrices")
#Solution for Computing Cross Product.
output = np.cross(A,B)
print(output)

Here's the original value of given matrices
[2 7 4] [3 9 8]
Here's the Cross Product of matrices
[20 -4 -3]
