<a href="https://colab.research.google.com/github/JhericoBunao/jhericobunao/blob/main/PythonExercise2_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Vector spaces and its operation**

In [1]:
import numpy as np

A = np.array([4,3])
B = np.array([2,-5])
print('Vector A is',A)
print('Vector B is',B)

Vector A is [4 3]
Vector B is [ 2 -5]


In [11]:
#checking shapes
#Shapes tells how many rows/columns are there.
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
pool = np.array([ball1,ball2])
print(pool.shape)
print(pool.size)
print(pool.ndim)

(2, 3)
6
2


In [13]:
R = A+B
print(R)

[ 6 -2]


In [16]:
R = np.add(A,B)
R

array([ 6, -2])

In [17]:
R = np.subtract(A,B)
R

array([2, 8])

In [18]:
A = np.array([1,5,8,9])
S = 5*A
print(S)

[ 5 25 40 45]


In [19]:
S = np.multiply(5,A)
print(S)

[ 5 25 40 45]


# **VECTOR CROSS PRODUCT**

In [22]:
#initialize arrays
import numpy as np
A = np.array([2,3,4])
B = np.array([1,7,0])

#Compute cross product
output = np.cross(A,B)
print(output)

[-28   4  11]


In [23]:
output = np.dot (A,B)
print(output)

23
